import React from "react";
import { useNavigate } from "react-router-dom";
import "../styles/TermsOfUse.css"; // Import the CSS file for styling

const TermsOfUse = () => {
    const navigate = useNavigate(); // ✅ This must be used
  
    const handleAccept = () => {
        localStorage.setItem("acceptedTerms", "true");
        window.location.href = "https://app.moyoledgers.com/login"; // ✅ Redirects properly
    };
  
    const handleDecline = () => {
      navigate("/access-denied"); // ✅ Use navigate when declining
    };

  return (
    <div className="terms-container">
      <div className="terms-box">
        {/* Icon */}
        <div className="terms-icon"><i class="ri-draft-line"></i></div>

        {/* Title */}
        <h1 className="terms-title">TERMS OF SERVICE</h1>

        {/* Description */}
        <p className="terms-summary">
          This summary is provided only for convenience. Please review the Terms
          of Service below in their entirety for important information and legal
          conditions that apply to your use of the platform for sharing and
          viewing online for mobile devices and personal computers.
        </p>

        {/* Scrollable Content */}
        <div className="terms-content">
        <p>
        These Terms of Use ("Terms") govern your access to and use of MoyoLedgers ("MoyoLedgers", "we", "us", or "our"), an AI-powered accounting assistant, 
        available through our website and associated services (collectively, the "Service"). By accessing or using MoyoLedgers, you 
        ("User", "you", or "your") agree to be bound by these Terms. If you do not agree to 
        these Terms, do not use the Service
          </p>
          <h3 className="term-heading">1. Use of the Service</h3>
          <p>
          You must be at least 18 years old to use MoyoLedgers. By using our Service, 
          you confirm that you have the legal capacity to enter into this agreement.
          </p>
          <p>
            MoyoLedgers provides AI-assisted accounting functionalities, 
            but it does not replace professional financial or legal advice. 
            You are responsible for verifying the accuracy of any financial 
            data or reports generated by the Service before making any business 
            or financial decisions.
          </p>
          <h3 className="term-heading">2. Account Registration</h3>
          <p>
           To use certain features of MoyoLedgers, you may need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted under your account.
          </p>
          <p>
           We reserve the right to suspend or terminate accounts that violate these Terms or engage in unauthorized use of the Service.
          </p>
          <h3 className="term-heading">3. Privacy and Data Security</h3>
          <p>
           Your use of MoyoLedgers is subject to our Privacy Policy, which outlines how we collect, use, and protect your personal and financial information. By using our Service, you agree to our data handling practices as described in the Privacy Policy.
          </p>
          <h3 className="term-heading">4. Subscription and Payments</h3>
          <p>
           Certain features of MoyoLedgers may require a paid subscription. By subscribing, you agree to pay the applicable fees, which are subject to change. Payments are processed by third-party payment providers, and we do not store your payment details.
          </p>
          <p>
           Subscription fees are non-refundable except where required by law. If you cancel your subscription, you will retain access until the end of the current billing cycle.
          </p>
          <h3 className="term-heading">5. Acceptable Use Policy</h3>
          <p>
          You agree not to:
          </p>
           <ul>
            <li>Use the Service for any illegal or fraudulent purposes.</li>
            <li>Interfere with the operation of the Service or attempt to gain unauthorized access.</li>
            <li>Upload or transmit malicious code, spam, or harmful content.</li>
            <li>Misuse AI-generated outputs for deceptive or unethical purposes.</li>
           </ul>
           <p>
           Violations of this policy may result in account suspension or termination.
           </p>
           <h3 className="term-heading">6. Intellectual Property</h3>
           <p>
           All content, trademarks, and technology used in MoyoLedgers are owned by us or licensed to us. You are granted a limited, non-exclusive, non-transferable right to use the Service for its intended purpose.
          </p>
          <p>
           You may not copy, modify, distribute, or reverse-engineer any part of MoyoLedgers without our prior written consent.
          </p>
          <h3 className="term-heading">7. Disclaimer of Warranties</h3>
          <p>
           MoyoLedgers is provided "as is" and "as available" without warranties of any kind. We do not guarantee that the Service will be error-free, secure, or uninterrupted. You use the Service at your own risk.
          </p>
          <h3 className="term-heading">8. Limitation of Liability</h3>
          <p>
           To the fullest extent permitted by law, MoyoLedgers shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability for any claims related to the Service shall not exceed the amount you paid in subscription fees within the past 12 months.
          </p>
          <h3 className="term-heading">9.Modifications to the Service and Terms</h3>
          <p>
           We reserve the right to modify or discontinue the Service at any time. We may also update these Terms, and continued use of MoyoLedgers after changes are posted constitutes acceptance of the revised Terms.
          </p>
          <h3 className="term-heading">10. Governing Law</h3>
          <p>
          These Terms are governed by the laws of Zimbabwe. Any disputes arising under these Terms shall be resolved in the courts of law.
          </p>
          <h3 className="term-heading">11. Contact Information</h3>
          <p>
           If you have any questions about these Terms, please contact us at support@moyoledgers.com.
          </p>
        </div>

        {/* Fading Effect */}
        <div className="fade-effect"></div>

        {/* Buttons */}
        <div className="terms-buttons">
          <button className="accept-btn" onClick={handleAccept}>ACCEPT</button>
          <button className="decline-btn" onClick={handleDecline}>DECLINE</button>
        </div>
      </div>
    </div>
  );
};

export default TermsOfUse;